### ISSUE TITLE
Review attributes are all in lowercase/camelcase

### ISSUE THREAD

**Issue by erennakdag** [shubhsk88/realbnb-frontend#7]
All of the attributes listed under reviews are lowercase (e.g. location, checkIn is in camel case)

It seems that the text for those attributes is set in components/common/ReviewScore.tsx, but I am not sure where the prop comes from or whether changing the prop's name field is possible. 

Instead of name, using name[0].toUpperCase() + name.slice(1) could be a possible solution but it would not fix 'checkIn'.

If permitted I would love to make the changes.

**Comment by shubhsk88** [comment]
Yeah sure would love to have those changes in your PR
